apiVersion: v1
kind: ConfigMap
metadata:
  name: dce-msr-frontend
data:
  application.properties: |
    jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=nsp://umserver-h:9000
    jms.DEFAULT_IS_JMS_CONNECTION.clientID=DEFAULT_IS_JMS_CLIENT
    jms.DEFAULT_IS_JMS_CONNECTION.enabled=true
    jms.DEFAULT_IS_JMS_CONNECTION.csqSize=0
    jms.DEFAULT_IS_JMS_CONNECTION.jndi_jndiAliasName=DEFAULT_IS_JNDI_PROVIDER

    jdbc.wmdb.dbURL=jdbc:wm:oracle://dbaas-std-noe.noe.edf.fr:1521;serviceName=EA7DEV1_S.noe.edf.fr
    jdbc.wmdb.userid=POC_CAAS_WEBM1
    jdbc.wmdb.password=$secret{WM_DB_PASSWORD}
    jdbc.wmdb.driverAlias=DataDirect Connect JDBC Oracle Driver
    jdbcfunc.ISCoreAudit.connPoolAlias=wmdb
    jdbcfunc.ISInternal.connPoolAlias=wmdb
    jdbcfunc.ProcessAudit.connPoolAlias=wmdb

    settings.watt.net.default.accept=application/json
    settings.watt.server.ns.lockingMode=none
    settings.watt.net.localhost=https://dce-msr-personnes:443

    user.Administrator.password=$secret{ADMIN_PASSWORD}

  applicationFile.properties:  |