kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: dce-msr-frontend-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: dce-msr-frontend
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90

