apiVersion: v1
kind: ConfigMap
metadata:
  name: msr-frontend
data:
  application.properties: |
    jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=nsp://umserver-0:9000
    jms.DEFAULT_IS_JMS_CONNECTION.clientID=DEFAULT_IS_JMS_CLIENT
    jms.DEFAULT_IS_JMS_CONNECTION.enabled=true
    jms.DEFAULT_IS_JMS_CONNECTION.csqSize=0
    jms.DEFAULT_IS_JMS_CONNECTION.jndi_jndiAliasName=DEFAULT_IS_JNDI_PROVIDER
    jms.DEFAULT_IS_JMS_CONNECTION.jndi_automaticallyCreateUMAdminObjects=true
    jms.DEFAULT_IS_JMS_CONNECTION.producerMaxRetryAttempts=30
    jms.DEFAULT_IS_JMS_CONNECTION.producerRetryInterval=1000

    globalvariable.SERVER.value=$env{SERVER}

    settings.watt.net.default.accept=application/json
    settings.watt.server.ns.lockingMode=none
    settings.watt.server.saveConfigFiles=false 
    settings.watt.server.audit.logFilesToKeep=1
    settings.watt.server.serverlogFilesToKeep=1
    settings.watt.server.stats.logFilesToKeep=1
    settings.watt.server.pipeline.processor=false
    statisticsdatacollector.monitorConfig.enabled=false

    user.Administrator.password=$secret{ADMIN_PASSWORD}


  applicationFile.properties:  |