kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: msr-frontend-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: msr-frontend
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90

